# Configuration for Zero-Shot Food Safety Hazard Detection

# Dataset
dataset:
  name: FSVH
  num_food_categories: 26
  num_visual_attributes: 48
  num_seen_classes: 20
  num_unseen_classes: 8
  image_size: [800, 800]
  
# Knowledge Graph
knowledge_graph:
  embedding_dim: 512
  hidden_dim: 256
  gcn_layers: 2
  threshold: 0.4
  dropout: 0.1
  
# Semantic Vectors
semantic:
  bert_model: "bert-base-uncased"
  embedding_dim: 768
  max_length: 128
  projection_dim: 512

# Detector
detector:
  backbone: "resnet101"
  pretrained: true
  feature_dim: 2048
  roi_pool_size: 7
  num_anchors: 9
  rpn_batch_size: 256
  rpn_positive_fraction: 0.5
  rpn_positive_iou: 0.7
  rpn_negative_iou: 0.3
  roi_batch_size: 128
  roi_positive_fraction: 0.25
  roi_positive_iou: 0.5
  roi_negative_iou: [0.1, 0.5]
  nms_threshold: 0.7
  detection_threshold: 0.05

# KEFS
kefs:
  knowledge_dim: 512
  hidden_dim: 256
  num_heads: 8
  dropout: 0.1
  attention_dropout: 0.1
  
# RFDM
rfdm:
  num_timesteps: 100
  noise_schedule: "linear"
  beta_start: 0.00085
  beta_end: 0.012
  condition_dim: 512
  hidden_dims: [512, 512, 512]
  
# Training
training:
  # Detector training
  detector_epochs: 100
  detector_batch_size: 8
  detector_lr: 0.0001
  detector_weight_decay: 0.0001
  detector_lr_decay_epochs: [60, 80]
  detector_lr_decay_factor: 0.1
  
  # KEFS training
  kefs_epochs: 100
  kefs_batch_size: 64
  kefs_lr: 0.00001
  kefs_weight_decay: 0.0001
  kefs_lr_decay_epochs: [60, 80]
  kefs_lr_decay_factor: 0.1
  
  # Loss weights
  lambda1: 0.1  # Region diffusion loss
  lambda2: 0.1  # Graph denoising loss
  alpha: 0.5    # Graph denoising trade-off
  
  # Unseen classifier training
  unseen_epochs: 50
  unseen_batch_size: 128
  unseen_lr: 0.001
  
  # Feature synthesis
  num_synthesized_features: 500
  
# Evaluation
evaluation:
  iou_threshold: 0.5
  max_detections: 100
  calibration_factor: 0.7  # For GZSD
  
# Data augmentation
augmentation:
  horizontal_flip: 0.5
  scale_range: [0.8, 1.2]
  color_jitter: 0.2
  
# System
system:
  num_workers: 4
  pin_memory: true
  gpu_ids: [0, 1, 2, 3]
  seed: 42
  save_frequency: 5
  log_frequency: 50
